defaults: &defaults
  host: localhost
  preload_models: false

development:
  <<: *defaults
  database: tradaculator_dev

test:
  <<: *defaults
  database: tradaculator_test

stage:
  <<: *defaults
  database: tradaculator_test

production:
  <<: *defaults
  database: tradaculator_test